apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "axiom.fullname" . }}-config
  labels:
    app.kubernetes.io/name: axiom
data:
  app-url: "{{ .Values.externalUrl }}"
  aximetrics-ingest-url: http://{{ template "axiom.fullname" . }}-db-service
  backlog-mode: legacy
  core-tracing-sample-rate: "0"
  dataset-limit: "100"
  db-query-runner-postgres-conns: "20"
  db-tracing-sample-rate: "0.0001"
  lambda-url: "{{ .Values.dbQueryRunner.lambdaUrl | default {{ template "axiom.fullname" . }}-db-query-fn }}"
  login-oauth-app-callback: http://localhost
  parallel-function-invocations: "16"
  postgres-conns: "20"
  pubsub-backend: redis
  query-batch-size: "512"
  server-debug: "0"
  skip-shutdown-block-flush: "1"
