apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "axiom.fullname" . }}-login
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "axiom.fullname" . }}-login
  replicas: {{ .Values.login.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "axiom.fullname" . }}-login
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ template "axiom.fullname" . }}-login
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: {{ template "axiom.fullname" . }}-login
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: axiom-login-pod
          image: "{{ .Values.login.image.repository }}:{{ .Values.login.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.login.image.pullPolicy }}
          args: ["serve", "login"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            {{- toYaml .Values.login.resources | nindent 12 }}
          {{- with .Values.login.envFrom }}
          envFrom:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
            - name: AXIOM_MODE
              value: self-host
            - name: AXIOM_LICENSE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: license-token
                  name: {{ template "axiom.fullname" . }}-secrets
            - name: AXIOM_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  key: postgres-url
                  name: {{ template "axiom.fullname" . }}-secrets
            - name: AXIOM_REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis-url
                  name: {{ template "axiom.fullname" . }}-secrets
            - name: AXIOM_LOGIN_OAUTH_APP_CALLBACK
              valueFrom:
                configMapKeyRef:
                  key: login-oauth-app-callback
                  name: {{ template "axiom.fullname" . }}-config
            - name: AXIOM_LOGIN_JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  key: login-jwt-public-key
                  name: {{ template "axiom.fullname" . }}-secrets
            - name: AXIOM_LOGIN_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: login-jwt-private-key
                  name: {{ template "axiom.fullname" . }}-secrets
            {{- range .Values.login.extraEnvs }}
            - name: {{ quote .name }}
              value: {{ quote .value }}
            {{- end }}
      {{- if or .Values.imagePullSecrets .Values.imageRegistryCredentials }}
      imagePullSecrets:
        {{- if .Values.imageRegistryCredentials }}
        - name: {{ template "axiom.fullname" . }}-registry
        {{- end }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ quote .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.login.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.login.podSecurityContext | nindent 8 }}
      {{- end }} 
      {{- with .Values.login.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.login.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.login.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
