{{- if not .Values.dbQueryRunner.lambdaUrl -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "axiom.fullname" . }}-db-query-fn
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "axiom.fullname" . }}-db-query-fn
  replicas: {{ .Values.queryFn.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "axiom.fullname" . }}-db-query-fn
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
      - name: axiomdb-query-fn-pod
        image: "{{ .Values.queryFn.image.repository }}:{{ .Values.queryFn.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.queryFn.image.pullPolicy }}
        ports:
        - containerPort: 9090
        resources:
          {{- toYaml .Values.queryFn.resources | nindent 10 }}
        {{- with .Values.queryFn.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: AXIOM_JAEGER_SAMPLE_RATE
          value: "0"
        {{- if .Values.sentryDsn }}
        - name: AXIOM_SENTRY_DSN
          value: {{ .Values.sentryDsn }}
        {{- end }}
        - name: AXIOM_STORAGE
          valueFrom:
            secretKeyRef:
              name: axiom-secrets
              key: storage-uri
        {{- range .Values.queryFn.extraEnvs }}
        - name: {{ quote .name }}
          value: {{ quote .value }}
        {{- end }}
      {{- if .Values.registryAccessToken }}
      imagePullSecrets:
        - name: axiom-registry
      {{- else if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.queryFn.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryFn.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryFn.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
