{{- if .Values.registryAccessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: axiom-registry
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "axiomImagePullSecret" . }}
{{- end }}