apiVersion: v1
kind: Secret
metadata:
  name: axiom-secrets
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
type: Opaque
data:
  license-token: {{ .Values.licenseToken | b64enc | quote }}
  postgres-url: {{ required "Postgres URL is required!" .Values.postgresUrl | b64enc | quote }}
  email-url: {{ required "Email URL is required!" .Values.emailUrl | b64enc | quote }}
  storage-uri: {{ template "axiomStorageURI" .Values.storage.primary }}
  {{- if .Values.storage.fallback.uri }}
  fallback-storage-uri: {{ template "axiomStorageURI" .Values.storage.fallback }}
  {{- end }}