name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: release
        run: |
          git remote -v
          ls -la
          git checkout -b "release-test"
          helm package . --destination docs
          helm repo index docs/ --url 'https://a-khaledf.github.io/axiom-helm-charts'
          ls -la
          git add .
          git commit -m "test-release"
          git push origin release-test
          gh pr create
