name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.actor != env.GITHUB_ACTOR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Print github env
        run: echo "$GITHUB_ENV"
        env:
          GITHUB_ENV: ${{ toJson(env) }}
      - name: release
        run: |
          branch_name=release-test-${{ github.sha }}

          git checkout -b $branch_name
          helm package . --destination docs
          helm repo index docs/ --url 'https://a-khaledf.github.io/axiom-helm-charts'
          git add .
          git commit -m "test-release"
          git push origin $branch_name
          gh pr create --title update-$branch_name --body testg
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
